owner: solve-it-once
repo: upptime
user-agent: KojBot
sites:
  - name: "Solve it once"
    url: https://solveitonce.com
  - name: "Brad Czerniak"
    url: https://bradczerniak.com
  - name: "Shelby Brad"
    url: https://shelbybrad.com
  - name: "Lower Barriers"
    url: https://lowerbarriers.org
  - name: "Zenput"
    url: https://www.zenput.com
  - name: "pgc"
    url: https://www.princegeorgescountymd.gov
  - name: "deneau"
    url: https://electdeneau.github.io
  - name: "frost"
    url: https://www.frostdrupal.com
  - name: "Stemteachers"
    url: https://stemteachers.asu.edu
  - name: "WalkUHome"
    url: https://walkuhome.com
  - name: "MGoBlog"
    url: https://mgoblog.com
  - name: "ICI SFF"
    url: https://www.securefinancialfuture.org
  - name: "World Challenge"
    url: https://worldchallenge.org
  - name: "rf IDEAS"
    url: https://www.rfideas.com
  - name: "FDH"
    url: https://www.firstdentalhealth.com
  - name: "fibercore"
    url: https://fibercore.humaneticsgroup.com
  - name: "optek"
    url: https://optek.humaneticsgroup.com
  - name: "hitec"
    url: https://hitec.humaneticsgroup.com
  - name: "humanetics"
    url: https://www.humaneticsgroup.com
  - name: "sparrow"
    url: https://www.sparrow.org
  - name: "NDC"
    url: https://www.newdentalchoice.com
  - name: "EDS"
    url: https://www.employersdental.com
  - name: "DDS"
    url: https://www.diversifieddental.com
  #- name: "diamondchallenge"
  #  url: https://diamondchallenge.org
  #- name: "iqstrategix"
  #  url: https://www.iqstrategix.com
  #- name: "human element"
  #  url: https://www.human-element.com
  #- name: "geotech"
  #  url: https://www.geo-techsolutions.com
  #- name: "justice"
  #  url: https://www.justice.gov
  #- name: "lifestylelink"
  #  url: https://portal.lifestylelink.net
  #- name: "mdc"
  #  url: https://www.michigandesign.com
  #- name: "painless"
  #  url: https://painless-chiropractor.com
  #- name: "gmar"
  #  url: http://gmaronline.com
  #- name: "gtj"
  #  url: https://www.gtjfnmainspections.com
  #- name: "alec"
  #  url: https://alecinfo.org
  #- name: "beckwith"
  #  url: https://beckwithfloors.com
  #- name: "ccsem"
  #  url: https://ccsem.org
  #- name: "jmb"
  #  url: https://jmbfinancial.com
  #- name: "shifrin"
  #  url: https://shifrin-hayworth.com
  #- name: "tower"
  #  url: https://www.tower-construct.com
  #- name: "siena"
  #  url: https://www.sienaheights.edu
  #- name: "bw"
  #  url: https://www.bowerswilkins.com
  #- name: "eo"
  #  url: https://www.eotechinc.com
  #- name: "nypl"
  #  url: https://www.nypl.org
  #- name: "admissions umich"
  #  url: https://admissions.umich.edu
assignees:
  - ao5357
status-website:
  cname: status.solveitonce.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
