owner: solve-it-once
repo: upptime
user-agent: KojBot
sites:
  - name: "Solve it once"
    url: https://solveitonce.com
  - name: "Brad Czerniak"
    url: https://bradczerniak.com
  - name: "Shelby Brad"
    url: https://shelbybrad.com
  - name: "Lower Barriers"
    url: https://lowerbarriers.org
  - name: "Zenput"
    url: https://www.zenput.com
  - name: "bw"
    url: https://www.bowerswilkins.com
  - name: "iqstrategix"
    url: https://iqstrategix.com
  - name: "eo"
    url: https://www.eotechinc.com
  - name: "nypl"
    url: https://www.nypl.org
  - name: "axehead"
    url: https://axeheadwatch.com
  - name: "amulets"
    url: https://www.eloisemagicalamulets.com
  - name: "lifestylelink"
    url: https://portal.lifestylelink.net
  - name: "lldev"
    url: http://dev-lifestylelink-d7.pantheonsite.io/sites/all/modules/provisio_custom/provisio_notifications/Processor/pv_process_notifications.php
  - name: "mdc"
    url: https://www.michigandesign.com
  - name: "painless"
    url: https://painless-chiropractor.com
  - name: "gmar"
    url: http://gmaronline.com
  - name: "gtj"
    url: https://www.gtjfnmainspections.com
assignees:
  - ao5357
status-website:
  cname: status.solveitonce.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
